---
# tasks file for ansible-role-cyrus-sasl

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Get all SASL users
  shell: "{{ cyrus_sasl_sasldblistusers_command }} | cut -f1 -d':'"
  register: register_sasldblistusers
  changed_when: false

- name: Assert cyrus_sasl_sasldblistusers_command ran successfully
  assert:
    that:
      register_sasldblistusers.rc == 0

- name: Delete SASL users
  shell: "{{ cyrus_sasl_saslpassword_command }} -a '{{ item.value.appname }}' -u '{{ item.value.domain }}' -d -f '{{ cyrus_sasl_sasldb_file }}' '{{ item.key }}'"
  with_dict: "{{ cyrus_sasl_user }}"
  when:
    - item.value.state == 'absent'
    - item.key ~ '@' ~ item.value.domain in register_sasldblistusers.stdout_lines

- name: Create SASL users
  shell: "echo -n {{ item.value.password }} | {{ cyrus_sasl_saslpassword_command }} -a '{{ item.value.appname }}' -u '{{ item.value.domain }}' -c -p -f '{{ cyrus_sasl_sasldb_file }}' {{ item.key }}"
  with_dict: "{{ cyrus_sasl_user }}"
  when:
    - item.value.state == 'present'
    - not item.key ~ '@' ~ item.value.domain in register_sasldblistusers.stdout_lines
